package{
public var PrefBox2d:Array = [
	{'name': '北海道',   'zoom': 1.0},
	{'name': '青森県',   'zoom': 2.5},
	{'name': '岩手県',   'zoom': 2.0, 'r': 0.2},
	{'name': '秋田県',   'zoom': 2.0},
	{'name': '宮城県',   'zoom': 2.0},
	{'name': '山形県',   'zoom': 2.5, 'r': 0.95},
	{'name': '福島県',   'zoom': 2.2, 'r': .7},
	{'name': '茨城県',   'zoom': 2.5, 'r': .86},
	{'name': '栃木県',   'zoom': 2.0, 'r': .97, 'f': 0.01},
	{'name': '群馬県',   'zoom': 2.0},
	{'name': '埼玉県',   'zoom': 2.0},
	{'name': '千葉県',   'zoom': 2.0},
	{'name': '東京都',   'zoom': 3.0, 'r': .3},
	{'name': '神奈川県', 'zoom': 4.0},
	{'name': '新潟県',   'zoom': 2.3},
	{'name': '山梨県',   'zoom': 3.0},
	{'name': '長野県',   'zoom': 2.2, 'r': .9},
	{'name': '富山県',   'zoom': 2.0},
	{'name': '石川県',   'zoom': 2.4, 'r': .66},
	{'name': '福井県',   'zoom': 2.0},
	{'name': '岐阜県',   'zoom': 2.0},
	{'name': '静岡県',   'zoom': 2.0},
	{'name': '愛知県',   'zoom': 3.0},
	{'name': '三重県',   'zoom': 3.8},
	{'name': '滋賀県',   'zoom': 4.0},
	{'name': '京都府',   'zoom': 2.0},
	{'name': '大阪府',   'zoom': 2.0},
	{'name': '兵庫県',   'zoom': 2.0},
	{'name': '奈良県',   'zoom': 2.0},
	{'name': '和歌山県', 'zoom': 2.0},
	{'name': '鳥取県',   'zoom': 2.0},
	{'name': '島根県',   'zoom': 2.0},
	{'name': '岡山県',   'zoom': 2.0},
	{'name': '広島県',   'zoom': 2.0},
	{'name': '山口県',   'zoom': 2.0},
	{'name': '徳島県',   'zoom': 2.0},
	{'name': '香川県',   'zoom': 2.0},
	{'name': '愛媛県',   'zoom': 2.0},
	{'name': '高知県',   'zoom': 2.0},
	{'name': "福岡県",   'zoom': 2.0},
	{'name': "佐賀県",   'zoom': 2.0},
	{'name': "長崎県",   'zoom': 2.0},
	{'name': "熊本県",   'zoom': 2.0},
	{'name': '大分県',   'zoom': 2.0},
	{'name': '宮崎県',   'zoom': 2.0},
	{'name': "鹿児島県", 'zoom': 2.0},
	{'name': "沖縄県",   'zoom': 2.0}
];
}